#deploy app from git hub
---
- name: "Deploying from git"
  hosts: prod
  become: yes
  vars_files:
    - variable.yml
  tasks:
    - name: "Installing Packages"
      yum:
        name: "{{ item }}"
        state: present
      loop:
        "{{ Packages }}"    

    - name: "service start"
      service:
        name: httpd
        state: started
      ignore_errors: yes

    - name: "conf copying"
      template:
        src: ./basilg_conf.tmpl
        dest: /etc/httpd/conf.d/basilg_shop.conf
      register: apache_conf
    
    - name: "cloning git"
      git:
        repo: "{{ repo_url }}"
        dest: "{{ clone_dest }}"
      register: clone_status
       
    - name: "Copy content to Document root "
      copy:
        src: "{{ clone_dest }}"
        dest: "/var/www/html/{{ hostname }}"
        remote_src: true

    - name: "restart httpd"
      service:
        name: "httpd"
        state: restarted
        enabled: true
      when: apache_conf is changed

    - name: "restart php-fpm" 
      service:
        name: "php-fpm" 
        state: restarted 
        enabled: true
      when: clone_status.changed

  
